`NumPy` is the fundamental package for scientific computing in Python. It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, discrete Fourier trasforms, and much more.

In [1]:
import numpy as np

In [2]:
list1 = [33, 34, 23, 12] #In here there are 4 dimensional if we look closely. 
list1

[33, 34, 23, 12]

# Creating Numpy array:

In [3]:
# np.array()
list1 = [11, 2, 4]
array1 = np.array(list1)

print("\nType of array")
print(type(array1))

print("\narray")
print(array1)


Type of array
<class 'numpy.ndarray'>

array
[11  2  4]


In [4]:
dir(array1) 

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [5]:
# How can we see the dimensions of the array:
array1.ndim

1

In [6]:
# How can we see the 2 dimensional array:
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)
print(type(array2))
print(array2.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [7]:
list3 = [[1,2,3,4],[4,5,6,7],[7,8,9,5], [7,8,9,5]]
array3 = np.array(list3)
print(array3)
print(type(array3))
print(array3.ndim)

[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 5]
 [7 8 9 5]]
<class 'numpy.ndarray'>
2


## Some of the array objects.

### 1. np.zeros(shape, dtype=float, order='C' )
It is mostly used for the sum in array

In [8]:
array_zero = np.zeros(5)
print(array_zero)

[0. 0. 0. 0. 0.]


In [9]:
array_zero2 = np.zeros((2,3))
print(array_zero2)

[[0. 0. 0.]
 [0. 0. 0.]]


<br>

### 2. np.ones(shape, dtype=float, order='C')

In [10]:
#1D
array_one = np.ones(5)
print(array_one)

[1. 1. 1. 1. 1.]


In [11]:
array_one = np.ones((2,3))
print(array_one)

[[1. 1. 1.]
 [1. 1. 1.]]


<br>

### 3. np.full(shape, fill_value, dtype=None, order='C', *, like=None)

In [12]:
#1D
array_full = np.full(shape=5, fill_value=3.2)
print(array_full)

[3.2 3.2 3.2 3.2 3.2]


In [13]:
print(array_full.dtype)

float64


In [14]:
array_full = np.full(shape=(2,3), fill_value=4)
print(array_full)

[[4 4 4]
 [4 4 4]]


In [15]:
print(array_full.dtype)

int32


In [16]:
# how to see the shape of the datatype
print(array_full.shape)

(2, 3)


<br>

### 4. np.arange() 

In [17]:
mydata = np.arange(0,20)
print(mydata)
print("\nDimension")
print(mydata.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Dimension
1


<br>

### 5. np.reshape(array_like, newshape, order)

In [18]:
mydata_reshaped = np.reshape(mydata, (4,5), order='C')
print(mydata_reshaped)
print("\nDimension")
print(mydata_reshaped.ndim)

print("\nDatatype")
print(mydata_reshaped.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Dimension
2

Datatype
int32


<br>

### 6. np.linspace(start=array_like, stop=array_like, num=.., endpoint=True, retstep=False, dtype=None, axis=0)

In [19]:
array_linspace = np.linspace(start=0, stop=10, num=5, endpoint=False)
print(array_linspace)  

[0. 2. 4. 6. 8.]


Here, `endpoint=False` represents that we should not take last number that is 10 we take only upto 9

Now lets take `start = array_like` and `end = array_like` and see how `axis` works in `np.linspace`

In [20]:
array_linspace2 = np.linspace(start=(2, 10), stop=(5, 20), num=4, axis=0)
print(array_linspace2)

[[ 2.         10.        ]
 [ 3.         13.33333333]
 [ 4.         16.66666667]
 [ 5.         20.        ]]


If we change `axis =1` it will change in row wise.

<br>

### 7. np.diag(v=array_like, k=0)

In [21]:
diag_array1 = np.diag(v=[4, 5, 6, 7], k=0)
print(diag_array1)
print("\nDatatype")
print(diag_array1.dtype)


[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]

Datatype
int32


In [22]:
diag_array2 = np.diag([4, 5, 6, 7], k=1)
print(diag_array2)

[[0 4 0 0 0]
 [0 0 5 0 0]
 [0 0 0 6 0]
 [0 0 0 0 7]
 [0 0 0 0 0]]


<br>

### 8. np.eye(N, M=None, k=0, dtype=<class 'float'> order='C', *, like=None)

In [23]:
array_eye = np.eye(N=5, M=5, k=1)
print(array_eye)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


<br>

### 9. np.identity(n, dtype=None, *, like=None)

In [24]:
# diagonal matrix with 1 > identity matrix
# less used in industry
array_identity = np.identity(5)
print(array_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<br>

### 10. np.random()

In [25]:
# Here we see 2 dimensions datatype
array_random_rand = np.random.rand(2, 3)
print(array_random_rand)
print("\ndimension")
print(f"{array_random_rand.ndim}D")

[[0.1200904  0.06876135 0.03266058]
 [0.53781739 0.28731287 0.93937041]]

dimension
2D


In [26]:
#np.random.rand
# here we see 3 dimensional datasets.
array_rand = np.random.rand(2, 3, 5)
print(array_rand)
print("\ndimension")
print(f"{array_rand.ndim}D")

[[[0.4308519  0.10245161 0.33457829 0.10772768 0.39392976]
  [0.66927756 0.37658523 0.66108183 0.53148867 0.08662397]
  [0.08592426 0.26406283 0.43763778 0.93586355 0.74005117]]

 [[0.27684139 0.27922388 0.94270599 0.07650751 0.90062022]
  [0.18887993 0.10047528 0.17657112 0.52656722 0.20950693]
  [0.36352952 0.39449677 0.24562009 0.83773061 0.26234377]]]

dimension
3D


In this example we see `three dimensions (3D)` model of data which means there are `5 elements` in `2 rows` of `3 different rows`.

In [27]:
# np.random.randint
array_randint = np.random.randint(low=10, high=50, size=(2, 3, 5))
print(array_randint)
print("\ndimension")
print(f"{array_randint.ndim}D")
print("\nshape")
print(array_randint.shape)

[[[22 27 22 16 17]
  [21 16 18 42 14]
  [42 33 39 27 17]]

 [[30 20 25 44 14]
  [12 37 47 21 31]
  [46 47 21 18 48]]]

dimension
3D

shape
(2, 3, 5)
