In [1]:
import numpy as np

In [2]:
array_randint = np.random.randint(low=10, high=50, size=(4, 3, 4))
print(array_randint)


[[[33 32 16 44]
  [29 14 29 19]
  [31 33 49 11]]

 [[30 26 14 29]
  [17 13 39 48]
  [13 22 46 37]]

 [[15 17 25 23]
  [21 14 34 13]
  [20 37 49 36]]

 [[38 15 40 40]
  [43 48 42 30]
  [38 23 21 25]]]

dimension
3D

shape
(4, 3, 4)


<br>

## Attributes

### ndim

In [3]:
#ndim
print("\ndimension")
print(f"{array_randint.ndim}D")



dimension
3D


### shape

In [4]:
# shape
print("\nshape")
print(array_randint.shape)


shape
(4, 3, 4)


### type

In [5]:
# dtype
print("\ndtype")
print(array_randint.dtype)


dtype
int32


### size

In [6]:
# size
print("\nsize")
print(array_randint.size)


size
48


### Transpose

In [7]:
# Transpose
print("\nTranspose")
print(array_randint.T)


Transpose
[[[33 30 15 38]
  [29 17 21 43]
  [31 13 20 38]]

 [[32 26 17 15]
  [14 13 14 48]
  [33 22 37 23]]

 [[16 14 25 40]
  [29 39 34 42]
  [49 46 49 21]]

 [[44 29 23 40]
  [19 48 13 30]
  [11 37 36 25]]]


<br>

## Array Methods/Operations

In [8]:
## Array Methods/ Operations
array_randint = np.random.randint(low=10, high=50, size=(3, 4))
print(array_randint)

[[34 43 27 33]
 [28 46 39 44]
 [32 10 23 49]]


### Addition


In [9]:
array_randint.sum(axis=1) #Rows wise addition

array([137, 157, 114])

### Maximum

In [13]:
array_randint.max(axis = 0) #Colimn wise finding maximum

array([34, 46, 39, 49])

### Index Maximum

In [14]:
array_randint.argmax(axis = 1)

array([1, 1, 3], dtype=int64)

### Flatten

In [16]:
array_randint.flatten() # It will change the multi dimensions into 1D.

array([34, 43, 27, 33, 28, 46, 39, 44, 32, 10, 23, 49])

### Shape

In [31]:
array_randint.shape

(3, 6)

### Reshape

In [33]:
array_randint.reshape(2,9)

array([[40, 45, 42, 15, 25, 49, 13, 46, 19],
       [48, 11, 46, 26, 19, 13, 48, 33, 37]])

### Concatenate

In [34]:
#Concat
m = np.array([[1, 2], [3, 4]])
n = np.array([[5, 6], [7, 8]])

print(m)
print('-' * 20)
print(n)

[[1 2]
 [3 4]]
--------------------
[[5 6]
 [7 8]]


In [35]:
np.concatenate((m, n), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
np.concatenate((m, n), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

<br>

### Split()

In [2]:
# Lets see how it function in list and then in array.
string = "Hello how are you"
print(string.split(" "))

['Hello', 'how', 'are', 'you']


In [38]:
#Lets see it split in array
array_randint = np.random.randint(low=10, high=50, size=(3, 6))
print(array_randint)

[[19 22 40 41 13 34]
 [46 16 33 25 31 38]
 [11 33 46 25 20 40]]


In [39]:
np.split(array_randint, indices_or_sections=3)  #Split as according with indices

[array([[19, 22, 40, 41, 13, 34]]),
 array([[46, 16, 33, 25, 31, 38]]),
 array([[11, 33, 46, 25, 20, 40]])]

In [50]:
array_flatten = array_randint.flatten()
print(array_flatten)

[19 22 40 41 13 34 46 16 33 25 31 38 11 33 46 25 20 40]


In [52]:
np.split(array_flatten, [2, 3, 10, 12]) # Split as according with sections.

[array([19, 22]),
 array([40]),
 array([41, 13, 34, 46, 16, 33, 25]),
 array([31, 38]),
 array([11, 33, 46, 25, 20, 40])]

<br>

### np.diag()

In [6]:
arr = np.random.randint(1, 100, (5,5))
print(arr)
print("\nDimension")
print(f"{arr.ndim}D")
print("\nShape")
print(arr.shape)
print("\nSize")
print(arr.size)
print("\nData type")
print(arr.dtype)


[[ 3 91 81 86  4]
 [26 58 61 50 35]
 [38 78 46 78 98]
 [18 70 19 48 61]
 [35 41 82 44 41]]

Dimension
2D

Shape
(5, 5)

Size
25

Data type
int32


In [5]:
np.diag(arr, k=0) 

array([28, 62, 20, 36, 21])

<br>

### np.fill_diagonal

In [23]:
arr1 = np.random.randint(1, 100, (5,5))
print(arr1)
print("\nDimension")
print(f"{arr1.ndim}D")
print("\nShape")
print(arr1.shape)
print("\nSize")
print(arr1.size)
print("\nData type")
print(arr1.dtype)



[[20 71 98 86 58]
 [13 91 10 66 98]
 [46 18 83 33  1]
 [95 89 92 27 38]
 [50 48  5 17 79]]

Dimension
2D

Shape
(5, 5)

Size
25

Data type
int32


In [29]:
new_arr1 = np.fill_diagonal(arr1, 0)
print(arr1)

[[ 0 71 98 86 58]
 [13  0 10 66 98]
 [46 18  0 33  1]
 [95 89 92  0 38]
 [50 48  5 17  0]]


<br>

### np.newaxis()

In [32]:
x = np.arange(3)
print(x)

x[:, np.newaxis]

[0 1 2]


array([[0],
       [1],
       [2]])