In [33]:
import numpy as np


# Advance NumPy Operations:

## Numpy Broadcasting:

In `NumPy`, we can perform mathematical operations an arrays of different shapes. An array with a smaller shape is expanded to match the shape of a larger one. This is called broadcasting.

Let's see example:

In [13]:
array1 = np.array([1,2,3]) # Create 1D array
array2 = np.array([[1], [2], [3]]) # Create 2D array
print("\nArray 1")
print(array1)
print("\nArray 2")
print(array2)
print("-" * 20)
result = array1 + array2 # size of array1 expands to match with array2
print(result)


Array 1
[1 2 3]

Array 2
[[1]
 [2]
 [3]]
--------------------
[[2 3 4]
 [3 4 5]
 [4 5 6]]


<br>

### Compatibility Rules for Broadcasting
- Broadcasting only works with compatible arrays. NumPy compares a set of array dimensions from right to left.
- Every set of dimensions must be compatible with the arrays to be broadcastable. A set of demensions lengths is compatible when
  1. one of them has a length of 1 or
  2. they are equal

In [14]:
# Example:
print("\n Array1 Shape")
print(array1.shape)
print("\n Array2 Shape")
print(array2.shape)


 Array1 Shape
(3,)

 Array2 Shape
(3, 1)


- Here `array1` and `array2` are arrays with different shape `(3, )` and `(3,1)` respectively.
- The dimension length 0 and 1 are compatible because one of them is 1.
- Similarly **3** and **3** are compatible since they are the same.
- As both sets of dimensions are compatible, the arrays are broadcastable.

In [19]:
array1 = np.random.rand(3, 1)
array2 = np.random.rand(4,2)
result = array1 + array2
print(result)

ValueError: operands could not be broadcast together with shapes (3,1) (4,2) 

In this example `array1` and `array2` are arrays with different shapes `(3,1)` and `(4,2)` respectively. The length `1` and `2` are compatible because one of them is `1`. But it cannot be broadcastable because they are not same i.e., `3` and `4` and are not compatible.

In [22]:
# Lets make this compatible and broadcastable.
array1 = np.random.rand(3, 1)
array2 = np.random.rand(3,2)
result = array1 + array2
print(result)

[[1.25910876 1.20019668]
 [1.50650565 0.8992265 ]
 [0.51413895 1.1908823 ]]


<br>

### Broadcasting with Scalars
We can also perform mathematical operations between arrays and scalars(single values). For exanple,

In [24]:
# 1-D array
array1 = np.array([1,2,3])

# scalar
num = 5

#add scalar and 1-D array
sum = array1 + num
print(sum)

[6 7 8]


In [32]:
array1 =np.random.rand(2,2,2,2)
num = 5
print(array1 + num)

[[[[5.40654386 5.67389736]
   [5.73329824 5.90889493]]

  [[5.8866882  5.08682771]
   [5.27944093 5.68810201]]]


 [[[5.89764341 5.80855757]
   [5.89635246 5.06524823]]

  [[5.20011623 5.39944054]
   [5.1685635  5.01525665]]]]


<br><br>

## NumPy Boolean Indexing:

- In NumPy, boolean indexing allows us to filter elements from an array based on a specific condition.
- We use boolean masks to specify the condition.

#### What is Boolean Masks in NumPy?
Boolean mask in a numpy array containing truth values(True/False) that correspond to each element in the array.

#### 1D

In [34]:
arr1 = np.array([1, 2, 3, 4, 5, 7, 8, 9, 7])
mask = arr1>5
print(mask)


[False False False False False  True  True  True  True]


In [35]:
# Lets find out number more than 5.
print(arr1[mask])


[7 8 9 7]


In [36]:
# Create an array of integers
array1 = np.array([1, 3, 5, 7, 8, 16, 22, 24, 25, 26, 28, 51, 52, 47])

# Create a boolean mask using combined logical operators
boolean_mask = (array1 < 10) | (array1 > 40)

# Apply the boolean mask to the array
result = array1[boolean_mask]
print(result)

[ 1  3  5  7  8 51 52 47]


#### Modify Elements Using Boolean Indexing.
In numpy, we can use boolean indexing to modify elements of the array. For example:

In [37]:
import numpy as np

# Create an array of numbers
numbers = np.array([1, 3, 5, 10, 7, 8, 9, 6])

# make a copy of the array
number_copy = numbers.copy()

# Change all even numbers to O in the copy
number_copy[numbers % 2==0] = 0

# Print the modified copy
print(number_copy)

[1 3 5 0 7 0 9 0]


<br>

#### 2D

In [40]:
arr2 = np.array([[1,4], [2, 4], [5, 6], [7, 8]])
print(arr2)

[[1 4]
 [2 4]
 [5 6]
 [7 8]]


In [42]:
mask = arr2 % 2== 0
print(mask)
print("\nElemensts out of arr2 when mask is True")
print(arr2[mask])

[[False  True]
 [ True  True]
 [False  True]
 [False  True]]

Elemensts out of arr2 when mask is True
[4 2 4 6 8]


In [12]:
# Print the elements of arr2 when mask is True
for i in range(mask.shape[0]):
    for j in range(mask.shape[1]):
        if mask[i, j]:
            print(arr2[i, j])

4
2
4
6
8


In [38]:
# Create a 2D array
array1 = np.array([[1, 7, 9],
                   [8, 9, 10],
                   [12, 14, 19]])

# Create a boolean mask based on the condition that elements are greater than 8
boolean_mask = array1>8

# Select only the elements that satisfy the condition:
print(array1[boolean_mask])

[ 9  9 10 12 14 19]


<br><br>

## NumPy Set Operations

### Set Union Operation in NumPy
In NumPy, we use the `np.union1d()` function to perform the set union operation in an array.Example:

In [43]:
a = np.array([1,2,3])
b = np.array([0,3,4])

#unions of two arrays
result = np.union1d(a , b)
print(result)

[0 1 2 3 4]


Note: `np.union1d(a , b)` is equivalent to `A U B` set operation.

<br>

### Set Intersection Operation in NumPy
We use the `np.intersect1d()` function to perform the set intersection operation in an array. For example,

In [45]:
a = np.array([1,2,3])
b = np.array([0,3,4])

# Intersection of two arrays
result = np.intersect1d(a, b)
print(result)

[3]


Note: `np.intersect1d(A,B)` is equivalent to `A ⋂ B` set operation.

<br>

### Set Difference Operation in NumPy
We use the `np.setdiff1d()` function to perform the difference between two arrays. For example,

In [46]:
a = np.array([1,2,3])
b = np.array([0,3,4])

# Difference of two arrays
result = np.setdiff1d(a, b)
print(result)

[1 2]


Note: `np.setdiff1d(A,B)` is equivalent to `A - B` set operation.

In [50]:
A = np.array([[1,2,3],
              [2,4, 5]])
B = np.array([[2,5,6],
              [5,7, 8]])
print(np.union1d(A, B))
print(np.setdiff1d(A,B))

[1 2 3 4 5 6 7 8]
[1 3 4]


<BR>

### Set Symmetric Difference Operation in NumPy
- The symmetric difference between two sets A and B includes all elements of A and B without the common elements.
- In NumPy, we use the `np.setxor1d()` function to perform symmetric differences between two arrays. For example,

In [51]:
a = np.array([1,2,3])
b = np.array([0,3,4])

# symmetric difference of two arrays
result = np.setxor1d(a, b)
print(result)

[0 1 2 4]


<br>

### Unique Values From a NumPy Array:
To select the unique elements from a NumPy array, we use the `np.unique()` function. 

In [53]:
array1 = np.array([2, 3, 3, 4, 4, 5, 5, 7, 7, 8, 8, 9, 9, 10, 11, 12, 12, 13])
# Unique values from array1
result = np.unique(array1)
print(result)

[ 2  3  4  5  7  8  9 10 11 12 13]


<br><br>

## NumPy Vectorization:
NumPy vectorization involves performing mathematical operations on entire arrays, eliminating the need to loop through individual elements.

In [55]:
import numpy as np
import time

### Why NumPy Vectorization over Python's Loop?

In [59]:
# Numpy element_wise operation
a = np.random.rand(10000000)
b = np.random.rand(10000000)
start = time.time()
c = a + b
end = time.time()
numpy_execution = end - start

# Python's execution 
a = list(a)
b = list(b)
c = []
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])

end = time.time()
python_execution = end - start

In [60]:
print(f"{numpy_execution} is numpy execution which is faster than {python_execution}.")

0.17186331748962402 is numpy execution which is faster than 2.8751819133758545.


In [61]:
print(f"Numpy is {python_execution/numpy_execution} times faster.")

Numpy is 16.72946825054415 times faster.


<br>

### NumPy Vectorize() Function
In NumPy, every mathematical operation with arrays is automatically vectorized. So we don't always need to use the `vectorize()` function.

In [63]:


# array whose square we need to find
array1 = np.array([-1, 0, 2, 3, 4])

# function to find the square
def find_square(x):
    if x < 0:
        return 0
    else:
        return x ** 2
        
# vectorize() to vectorize the function find_square()
vectorized_function = np.vectorize(find_square)

# passing an array to a vectorized function
result = vectorized_function(array1)

print(result)

[ 0  0  4  9 16]
