# Types of Python

In [1]:
# Numeric
a = 24
b = 22
print(a+b)

46


In [2]:
type(a)

int

In [3]:
# Floating point Numbers:
a = 22.22
b = -22.012
type(a)

float

In [4]:
# Complex Numbers 
a = 22 + 3j
type(a)

complex

In [6]:
# Arithmetic Operations
a = 20
b = 30
# add
print(a+b)
# Subtract
print(a-b)
# Multiply
print(a*b)
# Divide with remainder
print(a%b)
# Divide
print(a/b)
# Exponential
print(a**b)
# Floor Division
print(b//a)

50
-10
600
20
0.6666666666666666
1073741824000000000000000000000000000000
1


In [9]:
# Type conversion
a = 20 
print(type(a))
y = float(a)
print(type(y))
z = complex(a)
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


In [10]:
# Comparision Operators 
a = 22
b = 12
# Greater than 
print(a>b)
#less than 
print(a<b)


True
False


In [11]:
# Math functions
import math 
from math import sqrt, cbrt
x = -5.5
print(abs(x))

5.5


In [13]:
x = 4
print(sqrt(x))
print(cbrt(x))

2.0
1.5874010519681994


### Python Text Types

In [14]:
greeting = "Hello, World!"
print(greeting)

Hello, World!


In [15]:
name = "Prabin Thapa"
print(f"{greeting}. My name is {name}.")

Hello, World!. My name is Prabin Thapa.


In [18]:
# Methods in string
x = "Mr. Prabin Thapa"
print(x.lower())
print(x.upper())
print(x.strip())

mr. prabin thapa
MR. PRABIN THAPA
Mr. Prabin Thapa


In [23]:
y = x.split('.')[1]
print(y)
print(y.strip())

 Prabin Thapa
Prabin Thapa


In [24]:
print(y.replace('P', 'S'))

 Srabin Thapa


In [25]:
# String Indexing
x = "Hello, People. What are you doing"
len(x)

33

In [26]:
print(x[22])

e


In [27]:
# String Slicing
print(x[0:33:2])

Hlo epe htaeyudig


In [28]:
print(x[::-1])

gniod uoy era tahW .elpoeP ,olleH


In [29]:
# String concatenation 
var1 = "hello"
var2 = "Good Morning"
var3 = "!, ".join([var1, var2])
print(var3)

hello!, Good Morning


In [32]:
# Write a function to return the full name by concatenating first name and last name.
def full_name(first_name, last_name):
    result = ' '.join([first_name, last_name])
    return result

obj = full_name('Prabin', 'Thapa')
print(obj)

Prabin Thapa


In [38]:
# Advanced String Formatting
# Alignment
x = "Hello world!"
print("{:>20}".format(x))
print("{:<20}".format(x))
print("{:^20}".format(x))

        Hello world!
Hello world!        
    Hello world!    


In [40]:
# Padding
print("{:_>20}".format(x))
print("{:.<20}".format(x))


________Hello world!
Hello world!........


In [42]:
# Sequences in python
# string -> Immutable
greeting = "Hello, World!"
print(greeting)

# list -> Mutable
x = list((11, 12, 13, 14))
print(x)
y = [1, 2, 3, 4, 5]
print(y)

# tuple -> Immutable
a = tuple((11, 12, 'hello'))
print(a)

Hello, World!
[11, 12, 13, 14]
[1, 2, 3, 4, 5]
(11, 12, 'hello')


In [49]:
# Accessing list items -> Indexing and Slicing
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(a[1]) #Indexing
print(a[-9])

#slicing
print(a[0:9])
print(a[0:9:2])

# Modifying list 
a[2] = 11
print(a)

2
2
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]
[1, 2, 11, 4, 5, 6, 7, 8, 9, 10]


In [3]:
a = [ 1, 2, 3, 4, "Prabin", "Sushma"]
len(a)

6

In [50]:
# Set
var1 = set(("Hari", "Ram", "Shyam"))
print(var1)

{'Ram', 'Hari', 'Shyam'}


In [4]:
list("hello")

['h', 'e', 'l', 'l', 'o']

In [6]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [51]:
# Python conditional Statement
## Check the given number is positive or negative or zero.
num = int(input("Enter a number"))
if num > 0:
    print(f"The given number {num} is a positive number.")
elif num == 0:
    print(f"The given number {num} is zero.")
else:
    print(f"The given number {num} is a negative number.")

Enter a number -1


The given number -1 is a negative number.


In [54]:
marks = int(input("Enter your marks."))

if marks <= 100 and marks > 80:    
    print("Grade A")
    
elif marks <= 80 and marks > 60:    
    print("Grade B")
    
elif marks <= 60 and marks> 40:    
    print("Grade C") 

else:
    print("Grade D")

Enter your marks. 55


Grade C


In [55]:
## Python for loop
fruits = ['apple', 'banana', 'mango']
for fruit in fruits:
    print(fruit)

apple
banana
mango


In [62]:
fruits = ['apple', 'banana', 'mango']
juice = ['milk', 'lassi']
for fruit in fruits:
    for j in juice:
        print(fruit, j)

apple milk
apple lassi
banana milk
banana lassi
mango milk
mango lassi


In [63]:
for i in range(5):
    print(i)

0
1
2
3
4


#### Write a program that takes a list of numbers as input and uses a for loop to calculate the following -Sum of all number, -Average, -Largest and smallest.


In [69]:
def calculation_statistics(numbers):
    '''
    This function takes a list of numbers and do calculation.
    Args:
        numbers: A list of numbers
    Returns:
        A dict containing the sum, avg, largest and smallest element.
    '''
    total_sum = 0
    largest_number = numbers[0]
    smalles_number = numbers[0]

    for number in numbers:
        total_sum += number
        largest_number = max(largest_number, number)
        smalles_number = min(smalles_number, number)

    average = total_sum / len(numbers)
    return {
        "Sum" : total_sum,
        "Average" : average,
        "Largest" : largest_number,
        "Smallest" : smalles_number
    }

numbers = input("Enter a list of numbers separated by spaces: ")
numbers_int = [int(num) for num in numbers.split()]
stats= calculation_statistics(numbers_int)
print("List statistics")
for key, value in stats.items():
    print(f"{key} : {value}")


Enter a list of numbers separated by spaces:  11 12 13 14


List statistics
Sum : 50
Average : 12.5
Largest : 14
Smallest : 11


#### Password Checker: Write a program that uses for loops to check if a password meets certain criteria. The criteria could include:
- Minimum length (e.g., 8 characters)
- Contains at least one uppercase letter
- Contains at least one lowercase letter
- Contains at leas one number

The program should print a message indicating if the password is valid or not based on these criteria.


In [70]:
def check_password(password):
    has_upper = False
    has_lower = False
    has_digit = False
    min_length = 8

    if len(password)< min_length:
        return False, "Password must be at least 8 characters long."

    for char in password:
        if char.isupper():
            has_upper = True
        elif char.islower():
            has_lower = True
        elif char.isdigit():
            has_digit = True

    if not has_upper:
        return False, "Password must contain at least one uppercase letter."
    if not has_lower:
        return False, "Password must contain at least one lowercase letter."
    if not has_digit:
        return False, "Password must contain at least one number."

    return True, "Password is valid."

password = "ExamplePassword123"
is_valid, message = check_password(password)
print(message)

Password is valid.


In [3]:
#Function in Python
# A simple Python function to check whether x is even or odd.
def oddeven(x):
    if x%2==0:
        print("even")
    else:
        print("odd")
    return 

print(oddeven(2))

even
None


In [5]:
# Write a code that includes default parameter inside it:
def myfun(x, y=22):
    print(x)
    print(y)
    return

myfun(x=21)

21
22


In [6]:
# Write a program to create a function that takes two arguments, name and age and print thier value.
def value(name, age):
    print(f"This person name is {name} and he/she is {age} years old.")
    return 

value1 = value("Prabin", 22)
print(value1)


This person name is Prabin and he/she is 22 years old.
None


In [15]:
# Create a function to accept a variable length of arguments and print average value.
def func1(*args, **kwargs):
    sum = 0
    for arg in args:
        sum += arg
    avg = sum/len(args)
    return avg

func1(11, 12, 13, 13)

12.25

In [16]:
# Create a function to accept a variable length of arguments and print thier value.
def func1(*args, **kwargs):
    for arg in args:
        print(arg)
    return 

func1(11, 12, 13, 13)

11
12
13
13


In [19]:
# Return multiplication value also it must return addition and subtraction:

def calculator(a, b):
    summation = a + b
    multiply = a * b
    subtraction = a - b
    return (summation, multiply, subtraction)

print(calculator(1, 2))

(3, 2, -1)


In [20]:
# Create a recursive funtion
def recurs(num):
    if num:
        return num + recurs(num-1)
    else:
        return 0

res = recurs(10)
print(res)

55


In [30]:
# Assign different name to function and call it through the new name:
def difname(name, age):
    print(f"My name is {name}. I am {age} years old.")
name1 = difname
print(name1("Punl", 21))

My name is Punl. I am 21 years old.
None


In [33]:
#Generate a Pyton list of all the even numbers between 4 to 30?
def evenlst(starts, ends):
    return [num for num in range(starts, ends+1) if num%2==0]

print(evenlst(4, 30))

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


In [41]:
# Write a function that checks if the number is prime number.
def primenum(num):
    if num<=1:
        return False
    for i in range(2, int(num**0.5)+1):
        if num%i==0:
            return False
    return True

print(primenum(22))
print(primenum(7))

False
True


In [43]:
# Write a function that takes a list of numbers and return the sum of all even numbers in the list
def evensum(num):
    return sum(n for n in num if n%2==0)

print(evensum([1, 2, 3, 4, 5, 6,7, 8, 9]))

20


## Class and Objects 

- Create class Library
- constructor , student name and dept
- Class attribute , total student count
- book lend, input book name , if he/she can lend it or not

In [8]:
book = [ 
    ("The Alchemist", 25),
    ("The Da Vinci Code", 30),
    ("A Brief History of Time", 15),
    ("Angels & Demons", 0),
    ("The Grand Design", 0),
    ("1984", 19)
]

In [9]:

class Library:
    st_count = 0
    def __init__(self, name, dept="Management"):
        self.books = [ 
        ("The Alchemist", 25),
        ("The Da Vinci Code", 30),
        ("A Brief History of Time", 15),
        ("Angels & Demons", 0),
        ("The Grand Design", 0),
        ("1984", 19)
        ]
        self.name = name
        self.dept = dept
        Library.st_count += 1

    def burrow_book(self, book_name):
        status = [book for name, quantity in self.books if (name == book_name) & (quantity > 0)]
        if status:
            print("Yes")
        else:
            print("No")

    @classmethod
    def stu_count(self):
        return self.st_count


In [10]:
std1 = Library("Punk", "Science")
std1.stu_count()


1

In [11]:
std1.burrow_book("The Alchemist")

Yes


In [12]:
std1.burrow_book("Angels & Demons")

No


In [13]:
# Write a Python Program to create a Vehicle class with max_speed and mileage instance attributes.
class Vehicle:
    def __init__(self, max_speed, mileage):
        self.max_speed = max_speed
        self.mileage = mileage

model1 = Vehicle(200, "Volvo")
model1.max_speed

200

In [14]:
# Create a vehicle class without any variables and methods.
class Vehicle:
    pass

In [16]:
# Create a child class Bus that will inherit all of the variables and methods of vehicle class.
class Vehicle:
    def __init__(self, name, speed):
        self.name = name
        self.speed = speed

class Bus(Vehicle):
    def __init__(self, name, speed, mileage):
        super().__init__(name, speed)
        self.mileage = mileage

bus= Bus("Volvo", 120, 44)
print(bus.name)
print(bus.speed)

Volvo
120


In [18]:
# Create a Bus class that inherits from the Vehicle class. Given the capacity argument of Bus.seating_capacity() a default value of 50.
class Vehicle:
    def __init__(self, name, mileage, speed):
        self.name = name
        self.mileage = mileage
        self.speed = speed

    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers."

class Bus(Vehicle):
    def __init__(self, name, mileage, speed):
        super().__init__(name, mileage, speed)

    def seating_capacity(self, capacity=50):
        return super().seating_capacity(capacity)

bus = Bus("Toyota", 45, 120)
print(bus.seating_capacity())

The seating capacity of a Toyota is 50 passengers.


In [19]:
# Define a property that must have the same vlaue for every class instance(obj)
# Define a class attribute color with a default value white. I.E. Every vehicle should be white.

class Vehicle:
    color = "White"  # Class Attribute

    def __init__(self, name, mileage, speed):
        self.name = name
        self.mileage = mileage
        self.speed = speed

class Bus(Vehicle):
    pass

class Car(Vehicle):
    pass

bus = Bus("Toyota", 22, 150)
print(f"{bus.color} {bus.name}, gives mileage of {bus.mileage}kms in the speed of {bus.speed}km/hr")

car = Car("Creta", 18, 180)
print(f"{car.color} {car.name}, gives mileage of {car.mileage}kms in the speed of {car.speed}km/hr")

White Toyota, gives mileage of 22kms in the speed of 150km/hr
White Creta, gives mileage of 18kms in the speed of 180km/hr


In [21]:
''' Create a Bus child class that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100.
    If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge. 
    So total fare for bus instance will become the final amount = total fare + 10% of the total fare.

Note: The bus seating capacity is 50. so the final fare amount should be 5500. 
You need to override the fare() method of a Vehicle class in Bus class.
'''
class Vehicle:
    color = "White" #Class Attribute
    def __init__(self, name, mileage, speed, capacity = 50):
        self.name = name
        self.mileage = mileage
        self.speed= speed
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100

class Bus(Vehicle):
    def fare(self):
        amount = super().fare()
        amount += amount * 0.1
        return amount

bus = Bus("Volvo", 22, 130)
print(bus.name)
print(bus.speed)
print(bus.capacity)
print("Total Bus fare is:", bus.fare())

Volvo
130
50
Total Bus fare is: 5500.0


In [22]:
# Determine if school_bus is also an instance of the Vehicle class.
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

class Bus(Vehicle):
    pass

school_bus = Bus("Volvo", 50, 34)
print(isinstance(school_bus, Vehicle))

True


In [7]:
import numpy as np

In [11]:
array1 = np.random.randint(10, 50, (2, 3, 5))
print(array1)
print("\ndimension")
print(array1.ndim)
print(array1.shape)

[[[19 34 47 44 18]
  [27 43 26 40 37]
  [10 17 28 22 23]]

 [[41 34 35 29 10]
  [27 42 28 44 37]
  [47 24 14 37 26]]]

dimension
3
(2, 3, 5)


In [12]:
array1[0, 2, 2]

28

In [13]:
import pandas as pd

In [15]:
data= {
    "name": "Bob",
    "age": 40,
    "place": "Kathmandu"
}

df1 = pd.DataFrame(data, index=[1])
df1

name  age      place
1  Bob   40  Kathmandu

In [16]:
data= {
    "name": ["Bob", "Shyam", "Hari"],
    "age": [12, 13, 14]
}
df2 = pd.DataFrame(data)
df2

name  age
0    Bob   12
1  Shyam   13
2   Hari   14

In [17]:
df = pd.read_csv("C:\\Users\\hp\\Downloads\\archive\\train.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [18]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [19]:
df.size

10692

In [20]:
df.shape

(891, 12)

In [22]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [24]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [26]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [27]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [28]:
# Accessing Data( Subsetting Dataframes in Pandas)

In [30]:
subset1 = df.PassengerId.head()
print(subset1)

0    1
1    2
2    3
3    4
4    5
Name: PassengerId, dtype: int64


In [32]:
subset2 = df[['Survived', 'Pclass']]
subset2.head()

Survived  Pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3

In [34]:
# Indexing and Slicing in Pandas
## indexing with loc
df.loc[[0, 3, 4], ['Name', 'Embarked']]


Name Embarked
0                       Braund, Mr. Owen Harris        S
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)        S
4                      Allen, Mr. William Henry        S

In [35]:
#Slicing
df.loc[1:5, "Name":"Embarked"]

Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q

In [37]:
# Exploration
# value counts()

df.value_counts("Sex", normalize=True)

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [38]:
df.value_counts("Embarked", normalize=False)

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [39]:
df.value_counts("Survived", normalize=False)

Survived
0    549
1    342
Name: count, dtype: int64

In [42]:
# Want to know how many male survived
filter1 = df[(df['Sex'] == 'male') & (df.value_counts("Survived"))]
filter1

C:\Users\hp\AppData\Local\Temp\ipykernel_16900\2585940025.py:2: FutureWarning: Operation between non boolean Series with different indexes will no longer return a boolean result in a future version. Cast both Series to object type to maintain the prior behavior.
  filter1 = df[(df['Sex'] == 'male') & (df.value_counts("Survived"))]


PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
0            1         0       3  Braund, Mr. Owen Harris  male  22.0      1   

   Parch     Ticket  Fare Cabin Embarked  
0      0  A/5 21171  7.25   NaN        S

In [43]:
df[df['Sex']=='male'].value_counts("Survived")

Survived
0    468
1    109
Name: count, dtype: int64

#### groupby

In [46]:
#groupby sex
grouped = df.groupby(by='Sex')
grouped.sum()

PassengerId  Survived  Pclass  \
Sex                                     
female       135343       233     678   
male         262043       109    1379   

                                                     Name       Age  SibSp  \
Sex                                                                          
female  Cumings, Mrs. John Bradley (Florence Briggs Th...   7286.00    218   
male    Braund, Mr. Owen HarrisAllen, Mr. William Henr...  13919.17    248   

        Parch                                             Ticket        Fare  \
Sex                                                                            
female    204  PC 17599STON/O2. 3101282113803347742237736PP 9...  13966.6628   
male      136  A/5 2117137345033087717463349909A/5. 215134708...  14727.2865   

                                                    Cabin  \
Sex                                                         
female  C85C123G6C103B78D33B28F33C23 C25 C27E101F E69D...   
male    E46D56A6C23 C25 C27B30C52C83F G73E31A5D10 D12D...   

                                                 Embarked  
Sex                                                        
female  CSSSCSSSSSCQSSQCQSCSSCQQSCSSSSSSSQSSSSSSQCSCSS...  
male    SSQSSSSQSSSSCSSCSCSCSCSQCSSCSCSCSSCCSSSSCSSSSS...

In [48]:
groupe = df[['Sex', 'Fare']].groupby('Sex')
groupe.sum()

Fare
Sex               
female  13966.6628
male    14727.2865

In [49]:
group_by_embarked = df[['Embarked', 'Fare', 'Age']].groupby(by='Embarked')
group_by_embarked.mean()

Fare        Age
Embarked                      
C         59.954144  30.814769
Q         13.276030  28.089286
S         27.079812  29.445397

In [51]:
# Handiling duplicates 
df.duplicated().sum()

0

In [52]:
df1 = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})

In [53]:
df1.duplicated().sum()

1

In [54]:
df1.drop_duplicates(inplace=True)

In [55]:
df1

brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [56]:
mean_age = df['Age'].mean()
df['Age'].fillna(value=mean_age, inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_16900\2895209214.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(value=mean_age, inplace=True)


In [58]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [59]:
df['Age'] = df['Age'].astype(np.int32)

In [60]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age              int32
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

#### Pandas DateTime

In [61]:
date_string = '2021-12-24 12:30:00'
date = pd.to_datetime(date_string)
print(date)


2021-12-24 12:30:00


In [62]:
df = pd.DataFrame({'date': ['2021-01-13', '2022-10-22', '2023-12-03']})
df['date'] = pd.to_datetime(df['date'])
df

date
0 2021-01-13
1 2022-10-22
2 2023-12-03

In [64]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df

date  year  month  day
0 2021-01-13  2021      1   13
1 2022-10-22  2022     10   22
2 2023-12-03  2023     12    3

In [65]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B'],
    'Value': [10, 15, 20, 25, 30, 35]
}
df = pd.DataFrame(data)

# applying multiple aggregation functions to a single column
result = df.groupby('Category')['Value'].agg(['sum', 'mean', 'max', 'min'])

print(result)

          sum       mean  max  min
Category                          
A          55  18.333333   30   10
B          80  26.666667   35   20


<br>

#### Supervised Machine Learning

In [66]:
data = pd.read_csv("clean_stat_data.csv")
data.head()

matric_gpa_%  accommodation_status  monthly_allowance  \
0     -0.365008             -0.395407          -1.095457   
1      1.794677             -0.395407          -0.464006   
2     -0.365008             -0.395407          -1.095457   
3      1.794677             -0.395407           0.167446   
4     -0.697268             -0.395407          -1.095457   

   scholarship_bursary_2023  study_hours_week  socialising_week  drinks_night  \
0                 -0.360505         -1.155375         -1.205451     -1.407833   
1                  2.773886         -1.155375         -1.205451     -0.571682   
2                 -0.360505         -0.362322         -0.498885     -1.407833   
3                 -0.360505         -0.362322          0.207681     -1.407833   
4                 -0.360505         -0.362322         -1.205451      0.264470   

   classes_missed_alcohol  modules_failed  in_relationship  ...  faculty_Law  \
0               -2.507187       -0.753244        -1.148268  ...    -0.172062   
1               -1.676764       -0.753244         0.870877  ...    -0.172062   
2               -2.507187       -0.753244         0.870877  ...    -0.172062   
3               -0.846341       -0.753244        -1.148268  ...    -0.172062   
4               -0.015919       -0.077699         0.870877  ...    -0.172062   

   faculty_Medicine and Health Services  faculty_Science  \
0                             -0.172062        -0.399073   
1                             -0.172062        -0.399073   
2                             -0.172062        -0.399073   
3                             -0.172062        -0.399073   
4                             -0.172062        -0.399073   

   year_in_2023_0th Year  year_in_2023_1st Year  year_in_2023_2nd Year  \
0              -0.056614              -0.762108               1.076392   
1              -0.056614              -0.762108               1.076392   
2              -0.056614               1.312151              -0.929029   
3              -0.056614              -0.762108               1.076392   
4              -0.056614              -0.762108               1.076392   

   year_in_2023_3rd Year  year_in_2023_4th Year  year_in_2023_Postgraduate  \
0               -0.38278              -0.151248                  -0.127412   
1               -0.38278              -0.151248                  -0.127412   
2               -0.38278              -0.151248                  -0.127412   
3               -0.38278              -0.151248                  -0.127412   
4               -0.38278              -0.151248                  -0.127412   

   target  
0    72.0  
1    75.0  
2    55.0  
3    84.0  
4    52.0  

[5 rows x 29 columns]

In [67]:
X = data.drop('target', axis=1).to_numpy()
y = data['target'].to_numpy()

In [68]:
y

array([72.  , 75.  , 55.  , 84.  , 52.  , 54.  , 75.  , 75.  , 64.  ,
       76.  , 75.  , 65.  , 55.  , 54.  , 62.  , 55.  , 76.  , 65.  ,
       69.  , 60.  , 55.  , 74.  , 70.  , 60.  , 54.  , 75.  , 63.  ,
       73.  , 57.  , 75.  , 78.  , 55.  , 70.  , 60.  , 61.  , 63.  ,
       60.  , 57.  , 74.  , 76.  , 80.  , 66.  , 80.  , 70.  , 65.  ,
       75.  , 63.  , 80.  , 65.  , 75.  , 65.  , 61.  , 76.  , 65.  ,
       58.  , 60.  , 65.  , 60.  , 58.  , 55.  , 71.  , 60.  , 70.  ,
       60.  , 64.  , 84.  , 60.  , 61.  , 66.  , 65.  , 53.  , 62.  ,
       65.  , 62.  , 61.  , 73.  , 60.  , 60.  , 64.  , 62.  , 69.  ,
       57.  , 60.  , 60.  , 66.  , 50.  , 70.  , 65.  , 72.  , 62.  ,
       76.  , 75.  , 88.  , 61.  , 52.  , 79.  , 56.  , 70.  , 60.  ,
       57.  , 64.  , 60.  , 74.  , 73.  , 51.  , 60.  , 60.  , 65.  ,
       54.  , 65.  , 64.  , 61.  , 68.  , 53.  , 73.  , 50.  , 64.  ,
       73.  , 73.  , 50.  , 68.  , 65.  , 71.  , 65.  , 60.  , 72.  ,
       70.  , 77.  ,

In [69]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [70]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [71]:
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

LinearRegression()

In [72]:
y_actual = y_test

In [74]:
y_predicted = linear_model.predict(x_test)

In [75]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [76]:
mean_absolute_error(y_actual, y_predicted)

6.705649965510293

In [77]:
mean_squared_error(y_actual, y_predicted)

69.59770639694536