# Numpy Array Operations:

## Matrix operations:
- Matrices are important because a lot of world's datas are stored in form of tables and matrices are one of the way to work with tables in python.
- Matrices are 2-dimesional arryas
Lets see some examples.

### 1. Element-wise operations:
You can perform element-wise operations like addition, subtraction, multiplication, and division on matrices. These operation are performed element by element.

In [6]:
import numpy as np

#Create two matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(A)
print("-" *20)
print(B)
#Element-wise addition
C = A + B

#Element-wise multiplication
D = A * B

print("\nElement-wise Addition:")
print(C)

print("\nElement-wise Multiplication:")
print(D)

print(A.ndim) #to see dimensions of the array.

[[1 2]
 [3 4]]
--------------------
[[5 6]
 [7 8]]

Element-wise Addition:
[[ 6  8]
 [10 12]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]
2


In [7]:
a = np.array([[4, 5, 6], [5, 7, 9]])
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Array a")
print(a)
print("-"*20)
print("Array b")
print(b)
print("-"*20)
#Element-wise addition
c = a + b
print(c)
print("-"*20)
# Element-wise subtraction
d = a -b
print(d)
print("-"*20)
# Element-wise multiplication
e = a*b
print(e)
print("-"*20)

Array a
[[4 5 6]
 [5 7 9]]
--------------------
Array b
[[1 2 3]
 [4 5 6]]
--------------------
[[ 5  7  9]
 [ 9 12 15]]
--------------------
[[3 3 3]
 [1 2 3]]
--------------------
[[ 4 10 18]
 [20 35 54]]
--------------------


<br>

### 2. Matrix Multiplication:
For matrix multiplication, you can use the `@` operator or the `np.dot()` function


`Matrix multiplication` is a fundamental operation in linear algebra. In `NumPy`, the `@` operator and the `np.dot()` function can be used to perform matrix multiplication. Here's how it works:

Given two matrices `A` and `B`, the matrix product `C = A @ B` or `C = np.dot(A, B)` is calculated as follows:

1. The number of columns in matrix `A` must be equal to the number of rows in matrix `B` for the multiplication to be valid. If this condition is not met, `NumPy` will raise a `ValueError`.

2. For each element in the resulting matrix `C`, the value is calculated as the `sum` of the products of the elements in the corresponding `row of A` and the corresponding `column of B`.

Here's a step-by-step explanation of how the matrix multiplication works in your example:

In [2]:
# Matrix multiplication
E = A @ B  # equivalent to np.dot(A, B)
print("\nMatrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix Multiplication:")
print(E)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Multiplication:
[[19 22]
 [43 50]]


In this example `matrix A` column is equal to row of `matrix B` after that the matrix multiplication is possible. After that column of `Matrix B` is multiplied by row of `Matrix A` and then added (i.e.,`19= 1*5+2*7`, `22 = 6*1 + 8*2` ).

<br>

### 3. Matrix Transpose:
We can transpose a matrix using the `.T` attribute or the `np.transpose()` function.

In [3]:
# Transpose of a matrix
A = np.array([[1,2],[3,4]])
F = A.T  # equivalent to np.transpose(A)
print("\nMatrix A:")
print(A)
print("\nTranspose of Matrix A:")
print(F)



Matrix A:
[[1 2]
 [3 4]]

Transpose of Matrix A:
[[1 3]
 [2 4]]


In [14]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

<br>

### 4. Matrix Inverse: 
You can find the inverse of a matrix using the `np.linalg.inv()` function. 
Note that not all matrices are invertible.

In [8]:
# Matrix inverse
A = np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)

print("Inverse of Matrix A:")
print(A_inv)

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
# Mathematical Inverse

a = np.array([[8, 5], [5, 7]])
a_adj = np.array([[7, -5], [-5, 8]])
a_inv = (1/np.linalg.det(a)) * a_adj
print(a_inv)

[[ 0.22580645 -0.16129032]
 [-0.16129032  0.25806452]]


In [10]:
np.linalg.inv(a) # Numpy way of doing it

array([[ 0.22580645, -0.16129032],
       [-0.16129032,  0.25806452]])

<br>

### 5. np.trace()

The`numpy.trace`e function returns the sum along the diagonals of an array. If the array is 2-D, it calculates the trace, which is the sum of the diagonal elements. If the array has more than two dimensions, it operates on the last two dimensions and returns the sum along the diagonals of the resulting 2-D arrays.

In [11]:
a = np.array([[4, 5, 6], [5, 7, 9]])
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Array a")
print(a)
print("-"*20)
print("Array b")
print(b)
print("-"*20)

Array a
[[4 5 6]
 [5 7 9]]
--------------------
Array b
[[1 2 3]
 [4 5 6]]
--------------------


In [12]:
np.trace(a) #It givess addition of diagonal 4+5.

11

In [13]:
np.trace(b, offset=1)

8

<br>

### 6. np.linalg.det(a):
Gives determinant of matrices:
- To find out determination of matrices you should have square matrix (i.e., 2 x 2, 3x3)

In [14]:
np.linalg.det(a) # Determination doesnot come out because matrix is not square matrix.

LinAlgError: Last 2 dimensions of the array must be square

In [15]:
g = np.random.randint(1, 20, (3,3))
print(g)
np.linalg.det(g)

[[ 2  1 10]
 [18 16 13]
 [ 3 15 19]]


2135.000000000001

<br>

### 7. np.linalg.eig(a)

In [16]:
np.linalg.eig(g)

EigResult(eigenvalues=array([35.+0.j        ,  1.+7.74596669j,  1.-7.74596669j]), eigenvectors=array([[-0.22941573+0.j        ,  0.26981874-0.47832178j,
         0.26981874+0.47832178j],
       [-0.6882472 +0.j        , -0.6804786 +0.j        ,
        -0.6804786 -0.j        ],
       [-0.6882472 +0.j        ,  0.41157244+0.25683287j,
         0.41157244-0.25683287j]]))

<br>

### 8. np.linalg.solve(a, b)

In [25]:
# Solve the system of equations 1x + 2y = 1 and 3x + 5y = 2:

a = np.array([[1, 2], [3, 5]])  
b = np.array([1, 2])
x = np.linalg.solve(a, b)
x

array([-1.,  1.])

In [26]:
# Check that the solution is correct:
np.allclose(np.dot(a, x), b)

True

<br>

## Extra Array methods

### 5. np.arange() 

In [4]:
import numpy as np
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


The `arange` function is used to create an array with evenly spaced values within a given interval.

<br>

### 6. np.reshape(array_like, newshape, order)

In [5]:
#Now changing this datasets into 2 dimensional arrays.
mydata_reshaped = np.reshape(mydata, (4,5), order='C')
print(mydata_reshaped)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Lets see about parameters in np.reshape:
- **`array_like`**: The array to be reshaped. This can be an ndarray, a list, or any array-like object.
- **`newshape`**: The new shape of the array. This can be a tuple of integers or a single integer. If it is a tuple, the elements define the size of each dimension of the reshaped array. If it is a single integer, it indicates that the array should be reshaped into a 1-D array of that length.
- **`order`**: Specifies the order in which the elements of the array are read. It can be `'C'` (row-major, default) or `'F'` (column-major). `'A'` means to read / write the elements in Fortran-like index  order if `a` is Fortran *contiguous* in memory, C-like orde   otherwise.


In [6]:
# checking reshape with different orders
mydata_reshaped = np.reshape(mydata, (4,5), order='F')
print(mydata_reshaped)
mydata_reshaped = np.reshape(mydata, (4,5), order='A')
print(mydata_reshaped)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


<br>

##  Matrices slicing

In [7]:
import numpy as np
mydata = np.arange(0,30)
mydata_reshaped = np.reshape(mydata, (5,6), order='C')
print(mydata_reshaped)
print(mydata_reshaped[2,2])
print(mydata_reshaped[3,5])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
14
23


In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
row1 = matrix[0,:]
column1 = matrix[:, 0]
subset = matrix[0:2, 1:3]
print(row1)
print(column1)
print(subset)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 4 7]
[[2 3]
 [5 6]]


## Why NumPy over Python's Loop?

In [67]:
import numpy as np
import time

In [68]:
# Numpy element_wise operation
a = np.random.rand(10000000)
b = np.random.rand(10000000)
start = time.time()
c = a + b
end = time.time()
numpy_execution = end - start


In [69]:
# Python's execution 
a = list(a)
b = list(b)
c = []
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])

end = time.time()
python_execution = end - start
         


In [70]:
print(f"{numpy_execution} is numpy execution which is faster than {python_execution}.")

0.18746256828308105 is numpy execution which is faster than 2.7951622009277344.


In [71]:
print(f"Numpy is {python_execution/numpy_execution} times faster.")

Numpy is 14.910508409907475 times faster.
