# Indexing Numpy Arrays

## One Dimension

In [2]:
import numpy as np
list1 = [22, 23, 24, 25]
list1[3]

25

In [3]:
array1 = np.array(list1)
print(array1)


[22 23 24 25]


In [4]:
print(array1[3])

25


<br>

## Multi-dimensional

In [6]:
# 2D Array > Similar to Matrix

list2 = [[2, 3, 4], [5, 6, 7]]
array2 = np.array(list2)
print(array2)

[[2 3 4]
 [5 6 7]]


In [8]:
# Lets try to asses `7` from the array2.
array2[1, 2]

7

In [9]:
# np.random.randint
array_randint = np.random.randint(low=10, high=50, size=(2, 3, 5))
print(array_randint)
print("\ndimension")
print(f"{array_randint.ndim}D")
print("\nshape")
print(array_randint.shape)

[[[27 20 29 34 48]
  [36 15 35 19 24]
  [39 40 48 38 44]]

 [[35 34 46 34 38]
  [44 13 30 39 23]
  [19 15 32 19 34]]]

dimension
3D

shape
(2, 3, 5)


In [11]:
# Assess the 32 from array_randint
array_randint[1, 2, 2]

32

In [12]:
array_randint1 = np.random.randint(low=10, high=50, size=(2, 3, 5, 4))
print(array_randint1)
print("\ndimension")
print(f"{array_randint1.ndim}D")
print("\nshape")
print(array_randint1.shape)

[[[[34 20 16 44]
   [45 49 23 28]
   [36 24 41 26]
   [38 47 16 24]
   [41 40 31 14]]

  [[21 24 44 13]
   [35 40 31 12]
   [26 12 16 16]
   [13 20 23 18]
   [24 19 31 13]]

  [[37 40 44 48]
   [13 10 36 47]
   [34 38 40 47]
   [37 16 29 22]
   [35 16 20 36]]]


 [[[41 40 48 16]
   [32 43 31 25]
   [19 33 23 27]
   [30 32 31 39]
   [19 42 30 38]]

  [[11 38 19 17]
   [42 48 12 30]
   [35 42 47 31]
   [45 23 27 40]
   [34 32 28 24]]

  [[32 47 18 43]
   [46 45 41 21]
   [16 38 35 25]
   [37 28 27 20]
   [17 11 40 20]]]]

dimension
4D

shape
(2, 3, 5, 4)


In [14]:
array_randint1[1, 1, 4, 2]

28

## Question for Indexing

#### Q1: Basic Indexing:
- Create a numpy array `arr` of shape(3,4) filled with random integers. Print the entire array
- Print the first row of the array
- print the last column of the array
- Print the element at the second row and third column.

In [16]:
array1 = np.random.randint(low=10, high=35, size=(3,4))
print(array1)
print("\nDimension")
print(f"{array1.ndim}D")
print("\nShape")
print(array1.shape)
print("\nSize")
print(array1.size)

[[20 16 18 17]
 [26 24 18 14]
 [32 14 20 14]]

Dimension
2D

Shape
(3, 4)

Size
12


In [10]:
# Print the first row of the array:
array1_sliced1 = array1[0]
print(array1_sliced1)

[12 30 26 26]


In [21]:
# print the last column of the array

for row in array1:
    print(row[-1])

17
14
14


In [22]:
# Print the element at the second row and third column.
array1_sliced3 = array1[1,2]
print(array1_sliced3)

18


<br>

#### Q2: Boolean Indexing:
- Create a numpy array `arr` of shape(6,6) filled with random intetegers between 1 and 10.
- Find and print all elements in `arr` that are greater than 5.
- Create a boolean array `mask` that indicates where the elements of `arr` are even.
- Print the elements of `arr` when `mask` is True

In [23]:
arr2 = np.random.randint(low=1, high=10, size=(6,6))
print(arr2)
print("\nDimension")
print(f"{arr2.ndim}D")
print("\nShape")
print(arr2.shape)
print("\nSize")
print(arr2.size)

[[8 8 6 5 3 3]
 [5 9 6 5 9 8]
 [4 2 1 3 9 2]
 [8 9 2 9 9 3]
 [9 8 7 1 6 1]
 [5 5 5 4 4 2]]

Dimension
2D

Shape
(6, 6)

Size
36


In [26]:
# Find and print all elements in arr that are greater than 5.
for row in arr2:
    for element in row:
        if element>5:
            print(element)

8
8
6
9
6
9
8
9
8
9
9
9
9
8
7
6


In [40]:
# Create a boolean array 'mask' that indicates where the elements of arr2 are even.
mask = arr2
#for row in mask:
    #for element in row:
        #if element%2==0:
            #print(element) #This will print the even numbers but we want boolean(i.e, True or False)

# Alternative
mask = arr2%2==0
print("\nBoolean array 'mask'")
print(mask)


Boolean array 'mask'
[[ True  True  True False False False]
 [False False  True False False  True]
 [ True  True False False False  True]
 [ True False  True False False False]
 [False  True False False  True False]
 [False False False  True  True  True]]


In [41]:
# Print the elements of arr2 when mask is True
for i in range(mask.shape[0]):
    for j in range(mask.shape[1]):
        if mask[i,j]:
            print(arr2[i, j])

8
8
6
6
8
4
2
2
8
2
8
6
4
4
2


<br>

#### Fancy Indexing:
- Create a numpy array `arr` of shape (5, 5) filled with random integers between 1 and 100.
- Create an array `indices` with five random integers between 0 and 4.
- Use fancy indexing to print the diagonal elements of `arr` using the indices from `indices`.
- Use fancy indexing to replace the diagonal elements of `arr` with zeros using the indices from `indices`.

In [62]:
# Create a numpy array arr of shape (5, 5) filled with random integers between 1 and 100.
arr = np.random.randint(1, 100, (5,5))
print(arr)
print("\nDimension")
print(f"{arr.ndim}D")
print("\nShape")
print(arr.shape)
print("\nSize")
print(arr.size)


[[33  3 75 92 41]
 [73 31 99 74 65]
 [93 34 95 36 96]
 [48 75 71  4 55]
 [50 88 19 25 98]]

Dimension
2D

Shape
(5, 5)

Size
25


In [64]:
np.fill_diagonal(arr, 0)
print(arr)

[[ 0  3 75 92 41]
 [73  0 99 74 65]
 [93 34  0 36 96]
 [48 75 71  0 55]
 [50 88 19 25  0]]


In [56]:
# Create an array indices with five random integers between 0 and 4.
indices = np.random.randint(0, 5, size=5)
print(indices)
print("\nDimension")
print(f"{indices.ndim}D")
print("\nShape")
print(indices.shape)
print("\nSize")
print(indices.size)

[1 0 2 0 2]

Dimension
1D

Shape
(5,)

Size
5


In [58]:
# Use fancy indexing to print the diagonal elements of arr using the indices from indices.
diagonal_element = arr[indices, indices]
print("Diagonal elements of arr using indices:", diagonal_element)

Diagonal elements of arr using indices: [96 76 78 76 78]


In [59]:
# Use fancy indexing to replace the diagonal elements of arr with zeros using the indices from indices
np.fill_diagonal(arr, 0)
print("arr with diagonal elements replaced by zeros:")
print(arr)

arr with diagonal elements replaced by zeros:
[[ 0 84 13 47 59]
 [46  0 35 20 11]
 [18 47  0 35 51]
 [16 61 77  0  9]
 [72 20 23  5  0]]


<br>

#### Q4: Advance Indexing:
- Create a numpy array `arr` of shape(7,7) filled with random integers between 1 and 50.
- Create an array `row_indices` containing indices of rows `[1, 3, 5]`.
- Create an array `col_indices` containing indices of columns `[0, 2, 4]`.
- Use advanced indexing to print the elements at the intersection of rows and columns specified by row_indices and col_indices.

In [65]:
# Create a numpy array arr of shape(7,7) filled with random integers between 1 and 50.
arr = np.random.randint(1, 50, (7,7))

# Create an array row_indices containing indices of rows [1, 3, 5].
row_indices = np.array([1, 3, 5])

# Create an array col_indices containing indices of columns [0, 2, 4].
col_indices = np.array([0, 2, 4])

# Use advanced indexing to print the elements at the intersection of rows and columns specified by row_indices and col_indices.
intersection_element = arr[row_indices[:, np.newaxis], col_indices]
print("Element at the intersection:")
print(intersection_element)

Element at the intersection:
[[18 32 22]
 [39 41 40]
 [45 34 27]]


<br><br>

# Slicing Numpy Arrays

## One Dimensions

In [21]:
# Lets see example of list slicing.
list1 = [2, 3, 4, 5, 6, 7]
sliced_list1= list1[0:-1:2]
print(sliced_list1)

[2, 4, 6]


In [22]:
# 1D 
array1 = np.array(list1)
print(array1)

[2 3 4 5 6 7]


In [20]:
#Slicing Array
sliced_array1 = array1[0: -1: 2]
print(sliced_array1)

[2 4 6]


<br>

## Two Dimensions

In [23]:
list2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
array2 = np.array(list2)
print(array2)
print("\ndimension")
print(f"{array2.ndim}D")
print("\nshape")
print(array2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

dimension
2D

shape
(2, 5)


In [26]:
sliced_array2 = array2[1:4, 0:3:1]
sliced_array2

array([[6, 7, 8]])

In [27]:
list2d = [[1, 2, 3, 4, 5, 6, 7, 8], [2, 3, 4, 5, 6, 7, 8, 9]]
array2d = np.array(list2d)


<br>

## Three Dimesions

In [28]:
array_randint = np.random.randint(low=10, high=50, size=(4, 3, 4))
print(array_randint)
print("\ndimension")
print(f"{array_randint.ndim}D")
print("\nshape")
print(array_randint.shape)

[[[17 42 13 44]
  [30 33 11 11]
  [23 29 39 28]]

 [[22 40 34 43]
  [20 39 36 42]
  [24 28 43 26]]

 [[46 43 36 26]
  [33 33 10 11]
  [12 35 40 31]]

 [[20 19 32 31]
  [29 19 15 38]
  [17 32 34 15]]]

dimension
3D

shape
(4, 3, 4)


In [33]:
sliced_array_randint = array_randint[2: , 0:2:, 0:2:]
print(sliced_array_randint)
print(sliced_array_randint.shape)

[[[46 43]
  [33 33]]

 [[20 19]
  [29 19]]]
(2, 2, 2)


<br>

## ND (number of dimensions)

In [34]:
array_randint = np.random.randint(low=10, high=50, size=(3, 2, 4, 3))
print(array_randint)
print("\ndimension")
print(f"{array_randint.ndim}D")
print("\nshape")
print(array_randint.shape)

[[[[14 43 13]
   [27 17 16]
   [34 18 10]
   [23 48 23]]

  [[15 21 18]
   [48 43 27]
   [44 12 18]
   [48 26 36]]]


 [[[12 28 44]
   [19 35 11]
   [14 12 36]
   [30 24 11]]

  [[29 37 19]
   [40 35 45]
   [49 31 39]
   [17 19 26]]]


 [[[40 10 21]
   [26 15 30]
   [27 38 21]
   [37 10 13]]

  [[44 10 32]
   [22 24 42]
   [19 11 46]
   [39 30 26]]]]

dimension
4D

shape
(3, 2, 4, 3)


In [37]:
sliced_array = array_randint[2::, 0:1:1, 1:3:1, 1:3:1]
sliced_array

array([[[[15, 30],
         [38, 21]]]])

<br>

## Questions for Slicing Arrays